language: android
jdk: oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-24
  - extra-android-m2repository
script: cd android_app && ./gradlew assembleDebug
deploy:
  provider: releases
  api_key:
    secure: NwSMe2Qyh9PXzhrJK06CQUCKE9itZWLCXYG8hCquKnKxK1rW3CXQeRXOSn35HcaB+O9PklVcUnfXIs+9JXrLu9R+xr7auJ/PoCv2HDy9pEFE971nqrpuBRJNOzjBj1/nzOIgj6Yk2aSKw0Q84DPGd8M2DAu4uM5evO+4JKTfehPYut52P5GUFMybCS6nBSgg77lYU5600BAbLMWl0tuNSLYaEX8StT95MHi81GgNmOCh4FnrH6Y1lCHuScsE4UbBaCA5CKv0WI3oPuGGb/y6c8kBm9YQoUkIZy/06WmK7aO56Z6u4YHLdShjGzl17UQrVG8z92aHlSnfRvizjgW0YjUfim/52Owm0lhzZLGkgBA6GUK+pEQlITpG/P7IVdOZpAtlcOQiOJN5TeeL1/R6vqcgxn/Jpx9+WV1EuWZoYkm+oOrPxdstz79tRExS1d5PXcTBZafA/qu5kKd0Qk4ym5Y53I8bXYO5vh1iYVVVLcH354C879wQvMLEL7A5Q0xnZnVNYwviX7xVmOVZ+Q5clxnzh4TR1+TZvY2vEkSP2lJ1lSkEItRLbv3Y9qXaxjJgAevDya5pat4m7TFtQafkJSiNsDfdz+xeoYaDcVjfg7DVsHcOSi9goGtb5fqcF5qhF2h0hq8lfOvkHTpWnTW7eYqF2HoCVmCOMSmdiX47IOI=
  file: openScale-dev-build.apk
  on:
    repo: baztian/openScale
